In [4]:
import pandas as pd

# Create the DataFrame
df = pd.DataFrame({'Numbers': [1,1,2,3,5,8,13,21]})
df['diff_1'] = df['Numbers'].diff(1)
df['diff_-1'] = -df['Numbers'].diff(-1)

df['shift_1'] = df['Numbers'].shift(1)
df['shift_-1'] = df['Numbers'].shift(-1)




print(df)

   Numbers  diff_1  diff_-1  shift_1  shift_-1
0        1     NaN     -0.0      NaN       1.0
1        1     0.0      1.0      1.0       2.0
2        2     1.0      1.0      1.0       3.0
3        3     1.0      2.0      2.0       5.0
4        5     2.0      3.0      3.0       8.0
5        8     3.0      5.0      5.0      13.0
6       13     5.0      8.0      8.0      21.0
7       21     8.0      NaN     13.0       NaN

In [3]:
import yfinance as yf

data = yf.download("AAPL", start="2024-01-01", end="2025-01-01")
data

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2024-01-02  184.532089  187.315382  182.792533  186.033072  82488700
2024-01-03  183.150391  184.770668  182.335277  183.120571  58414500
2024-01-04  180.824356  181.997307  179.800504  181.062914  71983600
2024-01-05  180.098709  181.669281  179.094742  180.903888  62303300
2024-01-08  184.452560  184.492330  180.416793  181.003268  59144500
...                ...         ...         ...         ...       ...
2024-12-24  257.916443  257.926411  255.009620  255.209412  23234700
2024-12-26  258.735504  259.814335  257.347047  257.906429  27237100
2024-12-27  255.309296  258.415896  252.782075  257.546826  42355300
2024-12-30  251.923019  253.221595  250.474615  251.952985  35557500
2024-12-31  250.144974  253.001833  249.156056  252.162760  39480700

[252 rows x 5 columns]

In [ ]:
# File: get_data.py

import pandas as pd
import numpy as np
import yfinance as yf
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

#average true value - simple moving average of the true range
def addATR(data, period=14):
    """
    Compute the Average True Range (ATR) manually.
    """
    # Calculate True Range (TR)
    data['TR'] = np.maximum(data['High'] - data['Low'], 
                            np.maximum(abs(data['High'] - data['Close'].shift(1)), 
                                       abs(data['Low'] - data['Close'].shift(1))))
    
    data['ATR'] = data['TR'].rolling(window=period).mean()
    
    return data

def addRSI(data):
    #RSI = 100 - 100/(1 + RS)
    #RS = avg gain/ avg loss
    delta = data['Close'].diff(1)
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)
    avg_gain = gain.rolling(window=14).mean()
    avg_loss = loss.rolling(window=14).mean()
    rs = avg_gain / avg_loss
    data['RSI'] = 100 - (100 / (1 + rs))

    return data

def get_apple_stock_split(days_lag = 5):
    # Download Apple stock data
    data = yf.download("AAPL", start="2014-01-01", end="2023-01-01")

    # Calculate moving averages and relative price change
    data[f'SMA_{days_lag}'] = data['Close'].rolling(window=days_lag).mean()
    data['SMA_10'] = data['Close'].rolling(window=10).mean()
    data['SMA_50'] = data['Close'].rolling(window=50).mean()

    # Set target as next difference in price
    data['Target'] = -data['Close'].diff(-1)

    # Create lag columns
    lags = {f'lag_{i}': data['Close'].diff(i) for i in range(1, days_lag + 1)}
    data = data.assign(**lags)

    # add RSI
    data = addRSI(data)

    #add atr
    data = addATR(data)

    # Add day of the week as an integer (Monday=0, ..., Friday=4)
    data['Day_of_Week'] = data.index.dayofweek
    
    # Drop rows with missing values
    data.dropna(inplace=True)

    # Features
    X = data[['SMA_10', 'SMA_50', f'SMA_{days_lag}', 'High', 'Close', 'Open','Volumn', 'Low', 'RSI', 'ATR', 'Day_of_Week'] + [f'lag_{i}' for i in range(1, days_lag + 1)]]
    # Target
    Y = data[['Target']]
    
    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    
    return X_train, X_test, y_train, y_test